/// Pre-populated exercise database — 204 exercises across 13 muscle groups.
/// Each entry: [name, primaryMuscle, secondaryMuscle, equipmentType]
class ExerciseSeedData {
  ExerciseSeedData._();

  static const List<List<String?>> exercises = [
    // ── CHEST (22) ──────────────────────────────────────────────
    ['Barbell Bench Press', 'chest', 'triceps', 'barbell'],
    ['Incline Barbell Bench Press', 'chest', 'shoulders', 'barbell'],
    ['Decline Barbell Bench Press', 'chest', 'triceps', 'barbell'],
    ['Close-Grip Bench Press', 'chest', 'triceps', 'barbell'],
    ['Dumbbell Bench Press', 'chest', 'triceps', 'dumbbell'],
    ['Incline Dumbbell Bench Press', 'chest', 'shoulders', 'dumbbell'],
    ['Decline Dumbbell Bench Press', 'chest', 'triceps', 'dumbbell'],
    ['Dumbbell Fly', 'chest', null, 'dumbbell'],
    ['Incline Dumbbell Fly', 'chest', 'shoulders', 'dumbbell'],
    ['Dumbbell Pullover', 'chest', 'back', 'dumbbell'],
    ['Cable Crossover', 'chest', null, 'cable'],
    ['Low Cable Crossover', 'chest', 'shoulders', 'cable'],
    ['High Cable Crossover', 'chest', null, 'cable'],
    ['Cable Fly', 'chest', null, 'cable'],
    ['Machine Chest Press', 'chest', 'triceps', 'machine'],
    ['Machine Incline Press', 'chest', 'shoulders', 'machine'],
    ['Pec Deck Machine', 'chest', null, 'machine'],
    ['Smith Machine Bench Press', 'chest', 'triceps', 'machine'],
    ['Push-Up', 'chest', 'triceps', 'bodyweight'],
    ['Diamond Push-Up', 'chest', 'triceps', 'bodyweight'],
    ['Wide Push-Up', 'chest', null, 'bodyweight'],
    ['Dip (Chest)', 'chest', 'triceps', 'bodyweight'],

    // ── BACK (28) ───────────────────────────────────────────────
    ['Barbell Deadlift', 'back', 'legs', 'barbell'],
    ['Barbell Row', 'back', 'biceps', 'barbell'],
    ['Pendlay Row', 'back', 'biceps', 'barbell'],
    ['T-Bar Row', 'back', 'biceps', 'barbell'],
    ['Barbell Shrug', 'back', null, 'barbell'],
    ['Sumo Deadlift', 'back', 'legs', 'barbell'],
    ['Rack Pull', 'back', null, 'barbell'],
    ['Dumbbell Row', 'back', 'biceps', 'dumbbell'],
    ['Dumbbell Shrug', 'back', null, 'dumbbell'],
    ['Dumbbell Reverse Fly', 'back', 'shoulders', 'dumbbell'],
    ['Chest-Supported Dumbbell Row', 'back', 'biceps', 'dumbbell'],
    ['Renegade Row', 'back', 'core', 'dumbbell'],
    ['Lat Pulldown', 'back', 'biceps', 'cable'],
    ['Close-Grip Lat Pulldown', 'back', 'biceps', 'cable'],
    ['Wide-Grip Lat Pulldown', 'back', null, 'cable'],
    ['Seated Cable Row', 'back', 'biceps', 'cable'],
    ['Face Pull', 'back', 'shoulders', 'cable'],
    ['Straight-Arm Pulldown', 'back', null, 'cable'],
    ['Cable Shrug', 'back', null, 'cable'],
    ['Machine Row', 'back', 'biceps', 'machine'],
    ['Machine Lat Pulldown', 'back', 'biceps', 'machine'],
    ['Assisted Pull-Up Machine', 'back', 'biceps', 'machine'],
    ['Smith Machine Row', 'back', 'biceps', 'machine'],
    ['Pull-Up', 'back', 'biceps', 'bodyweight'],
    ['Chin-Up', 'back', 'biceps', 'bodyweight'],
    ['Wide-Grip Pull-Up', 'back', null, 'bodyweight'],
    ['Inverted Row', 'back', 'biceps', 'bodyweight'],
    ['Superman Hold', 'back', 'glutes', 'bodyweight'],

    // ── SHOULDERS (22) ──────────────────────────────────────────
    ['Overhead Press', 'shoulders', 'triceps', 'barbell'],
    ['Behind the Neck Press', 'shoulders', 'triceps', 'barbell'],
    ['Barbell Upright Row', 'shoulders', null, 'barbell'],
    ['Bradford Press', 'shoulders', 'triceps', 'barbell'],
    ['Dumbbell Shoulder Press', 'shoulders', 'triceps', 'dumbbell'],
    ['Arnold Press', 'shoulders', 'triceps', 'dumbbell'],
    ['Dumbbell Lateral Raise', 'shoulders', null, 'dumbbell'],
    ['Dumbbell Front Raise', 'shoulders', null, 'dumbbell'],
    ['Dumbbell Rear Delt Fly', 'shoulders', 'back', 'dumbbell'],
    ['Seated Dumbbell Press', 'shoulders', 'triceps', 'dumbbell'],
    ['Lu Raise', 'shoulders', null, 'dumbbell'],
    ['Cable Lateral Raise', 'shoulders', null, 'cable'],
    ['Cable Front Raise', 'shoulders', null, 'cable'],
    ['Cable Rear Delt Fly', 'shoulders', 'back', 'cable'],
    ['Cable Upright Row', 'shoulders', null, 'cable'],
    ['Machine Shoulder Press', 'shoulders', 'triceps', 'machine'],
    ['Machine Lateral Raise', 'shoulders', null, 'machine'],
    ['Reverse Pec Deck', 'shoulders', 'back', 'machine'],
    ['Smith Machine Shoulder Press', 'shoulders', 'triceps', 'machine'],
    ['Handstand Push-Up', 'shoulders', 'triceps', 'bodyweight'],
    ['Pike Push-Up', 'shoulders', 'triceps', 'bodyweight'],
    ['Plate Front Raise', 'shoulders', null, 'barbell'],

    // ── BICEPS (16) ─────────────────────────────────────────────
    ['Barbell Curl', 'biceps', null, 'barbell'],
    ['EZ-Bar Curl', 'biceps', null, 'barbell'],
    ['Barbell Preacher Curl', 'biceps', null, 'barbell'],
    ['Barbell Drag Curl', 'biceps', null, 'barbell'],
    ['Dumbbell Curl', 'biceps', null, 'dumbbell'],
    ['Dumbbell Hammer Curl', 'biceps', 'forearms', 'dumbbell'],
    ['Incline Dumbbell Curl', 'biceps', null, 'dumbbell'],
    ['Concentration Curl', 'biceps', null, 'dumbbell'],
    ['Dumbbell Preacher Curl', 'biceps', null, 'dumbbell'],
    ['Zottman Curl', 'biceps', 'forearms', 'dumbbell'],
    ['Cable Curl', 'biceps', null, 'cable'],
    ['Cable Hammer Curl', 'biceps', 'forearms', 'cable'],
    ['High Cable Curl', 'biceps', null, 'cable'],
    ['Bayesian Curl', 'biceps', null, 'cable'],
    ['Machine Preacher Curl', 'biceps', null, 'machine'],
    ['Machine Curl', 'biceps', null, 'machine'],

    // ── TRICEPS (16) ────────────────────────────────────────────
    ['Skull Crusher', 'triceps', null, 'barbell'],
    ['EZ-Bar Skull Crusher', 'triceps', null, 'barbell'],
    ['Barbell Overhead Extension', 'triceps', null, 'barbell'],
    ['JM Press', 'triceps', 'chest', 'barbell'],
    ['Dumbbell Overhead Extension', 'triceps', null, 'dumbbell'],
    ['Dumbbell Kickback', 'triceps', null, 'dumbbell'],
    ['Single Dumbbell Overhead Extension', 'triceps', null, 'dumbbell'],
    ['Cable Pushdown', 'triceps', null, 'cable'],
    ['Rope Pushdown', 'triceps', null, 'cable'],
    ['Cable Overhead Extension', 'triceps', null, 'cable'],
    ['Reverse-Grip Pushdown', 'triceps', null, 'cable'],
    ['Machine Tricep Extension', 'triceps', null, 'machine'],
    ['Machine Dip', 'triceps', 'chest', 'machine'],
    ['Dip (Triceps)', 'triceps', 'chest', 'bodyweight'],
    ['Close-Grip Push-Up', 'triceps', 'chest', 'bodyweight'],
    ['Bench Dip', 'triceps', null, 'bodyweight'],

    // ── LEGS / QUADS (20) ───────────────────────────────────────
    ['Barbell Back Squat', 'legs', 'glutes', 'barbell'],
    ['Barbell Front Squat', 'legs', 'core', 'barbell'],
    ['Zercher Squat', 'legs', 'core', 'barbell'],
    ['Pause Squat', 'legs', 'glutes', 'barbell'],
    ['Overhead Squat', 'legs', 'shoulders', 'barbell'],
    ['Goblet Squat', 'legs', 'core', 'dumbbell'],
    ['Dumbbell Lunge', 'legs', 'glutes', 'dumbbell'],
    ['Dumbbell Bulgarian Split Squat', 'legs', 'glutes', 'dumbbell'],
    ['Dumbbell Step-Up', 'legs', 'glutes', 'dumbbell'],
    ['Dumbbell Squat', 'legs', 'glutes', 'dumbbell'],
    ['Leg Press', 'legs', 'glutes', 'machine'],
    ['Hack Squat', 'legs', 'glutes', 'machine'],
    ['Leg Extension', 'legs', null, 'machine'],
    ['Smith Machine Squat', 'legs', 'glutes', 'machine'],
    ['V-Squat Machine', 'legs', 'glutes', 'machine'],
    ['Pendulum Squat', 'legs', 'glutes', 'machine'],
    ['Sissy Squat', 'legs', null, 'bodyweight'],
    ['Bodyweight Squat', 'legs', null, 'bodyweight'],
    ['Bodyweight Lunge', 'legs', 'glutes', 'bodyweight'],
    ['Jump Squat', 'legs', 'glutes', 'bodyweight'],

    // ── HAMSTRINGS (14) ─────────────────────────────────────────
    ['Romanian Deadlift', 'hamstrings', 'glutes', 'barbell'],
    ['Stiff-Leg Deadlift', 'hamstrings', 'back', 'barbell'],
    ['Good Morning', 'hamstrings', 'back', 'barbell'],
    ['Barbell Hip Thrust (Hamstring)', 'hamstrings', 'glutes', 'barbell'],
    ['Dumbbell Romanian Deadlift', 'hamstrings', 'glutes', 'dumbbell'],
    ['Single-Leg Dumbbell RDL', 'hamstrings', 'glutes', 'dumbbell'],
    ['Dumbbell Stiff-Leg Deadlift', 'hamstrings', 'back', 'dumbbell'],
    ['Lying Leg Curl', 'hamstrings', null, 'machine'],
    ['Seated Leg Curl', 'hamstrings', null, 'machine'],
    ['Standing Leg Curl', 'hamstrings', null, 'machine'],
    ['Cable Pull-Through', 'hamstrings', 'glutes', 'cable'],
    ['Cable Leg Curl', 'hamstrings', null, 'cable'],
    ['Nordic Hamstring Curl', 'hamstrings', null, 'bodyweight'],
    ['Glute-Ham Raise', 'hamstrings', 'glutes', 'bodyweight'],

    // ── GLUTES (14) ─────────────────────────────────────────────
    ['Barbell Hip Thrust', 'glutes', 'hamstrings', 'barbell'],
    ['Barbell Glute Bridge', 'glutes', 'hamstrings', 'barbell'],
    ['Sumo Squat', 'glutes', 'legs', 'barbell'],
    ['Dumbbell Hip Thrust', 'glutes', 'hamstrings', 'dumbbell'],
    ['Dumbbell Sumo Squat', 'glutes', 'legs', 'dumbbell'],
    ['Dumbbell Frog Pump', 'glutes', null, 'dumbbell'],
    ['Cable Kickback', 'glutes', null, 'cable'],
    ['Cable Pull-Through (Glutes)', 'glutes', 'hamstrings', 'cable'],
    ['Smith Machine Hip Thrust', 'glutes', 'hamstrings', 'machine'],
    ['Machine Glute Kickback', 'glutes', null, 'machine'],
    ['Hip Abduction Machine', 'glutes', null, 'machine'],
    ['Glute Bridge', 'glutes', 'hamstrings', 'bodyweight'],
    ['Single-Leg Glute Bridge', 'glutes', 'hamstrings', 'bodyweight'],
    ['Donkey Kick', 'glutes', null, 'bodyweight'],

    // ── CORE (18) ───────────────────────────────────────────────
    ['Crunch', 'core', null, 'bodyweight'],
    ['Bicycle Crunch', 'core', null, 'bodyweight'],
    ['Reverse Crunch', 'core', null, 'bodyweight'],
    ['Sit-Up', 'core', null, 'bodyweight'],
    ['Leg Raise', 'core', null, 'bodyweight'],
    ['Hanging Leg Raise', 'core', null, 'bodyweight'],
    ['Hanging Knee Raise', 'core', null, 'bodyweight'],
    ['Plank', 'core', null, 'bodyweight'],
    ['Side Plank', 'core', null, 'bodyweight'],
    ['Mountain Climber', 'core', null, 'bodyweight'],
    ['Russian Twist', 'core', null, 'bodyweight'],
    ['V-Up', 'core', null, 'bodyweight'],
    ['Dead Bug', 'core', null, 'bodyweight'],
    ['Ab Wheel Rollout', 'core', null, 'bodyweight'],
    ['Cable Crunch', 'core', null, 'cable'],
    ['Cable Woodchop', 'core', null, 'cable'],
    ['Machine Crunch', 'core', null, 'machine'],
    ['Decline Sit-Up', 'core', null, 'bodyweight'],

    // ── CALVES (8) ──────────────────────────────────────────────
    ['Standing Calf Raise', 'calves', null, 'machine'],
    ['Seated Calf Raise', 'calves', null, 'machine'],
    ['Leg Press Calf Raise', 'calves', null, 'machine'],
    ['Smith Machine Calf Raise', 'calves', null, 'machine'],
    ['Barbell Calf Raise', 'calves', null, 'barbell'],
    ['Dumbbell Calf Raise', 'calves', null, 'dumbbell'],
    ['Single-Leg Calf Raise', 'calves', null, 'bodyweight'],
    ['Donkey Calf Raise', 'calves', null, 'bodyweight'],

    // ── FOREARMS (6) ────────────────────────────────────────────
    ['Barbell Wrist Curl', 'forearms', null, 'barbell'],
    ['Barbell Reverse Wrist Curl', 'forearms', null, 'barbell'],
    ['Dumbbell Wrist Curl', 'forearms', null, 'dumbbell'],
    ['Dumbbell Reverse Wrist Curl', 'forearms', null, 'dumbbell'],
    ['Farmer Walk', 'forearms', 'core', 'dumbbell'],
    ['Behind-the-Back Barbell Wrist Curl', 'forearms', null, 'barbell'],

    // ── CARDIO (10) ─────────────────────────────────────────────
    ['Treadmill Run', 'cardio', null, 'machine'],
    ['Stationary Bike', 'cardio', null, 'machine'],
    ['Elliptical', 'cardio', null, 'machine'],
    ['Rowing Machine', 'cardio', 'back', 'machine'],
    ['Stair Climber', 'cardio', 'legs', 'machine'],
    ['Assault Bike', 'cardio', null, 'machine'],
    ['Ski Erg', 'cardio', 'back', 'machine'],
    ['Burpee', 'cardio', 'full_body', 'bodyweight'],
    ['Jumping Jack', 'cardio', null, 'bodyweight'],
    ['Box Jump', 'cardio', 'legs', 'bodyweight'],

    // ── FULL BODY (10) ──────────────────────────────────────────
    ['Barbell Clean', 'full_body', null, 'barbell'],
    ['Barbell Snatch', 'full_body', null, 'barbell'],
    ['Clean and Press', 'full_body', null, 'barbell'],
    ['Barbell Thruster', 'full_body', null, 'barbell'],
    ['Dumbbell Thruster', 'full_body', null, 'dumbbell'],
    ['Dumbbell Snatch', 'full_body', null, 'dumbbell'],
    ['Man Maker', 'full_body', null, 'dumbbell'],
    ['Kettlebell Swing', 'full_body', 'glutes', 'kettlebell'],
    ['Kettlebell Turkish Get-Up', 'full_body', 'core', 'kettlebell'],
    ['Kettlebell Clean and Press', 'full_body', null, 'kettlebell'],
  ];
}
